"""clubs cascade3

Revision ID: 349ef58da19b
Revises: c041dc32dec4
Create Date: 2025-12-20 18:38:04.877761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349ef58da19b'
down_revision: Union[str, Sequence[str], None] = 'c041dc32dec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('players_club_id_fkey'), 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key(op.f('players_club_id_fkey'), 'players', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###
