"""clubs cascade5

Revision ID: 396597d6ee57
Revises: 3905f95a0e58
Create Date: 2025-12-20 18:54:06.541182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '396597d6ee57'
down_revision: Union[str, Sequence[str], None] = '3905f95a0e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('clubs_and_players_club_id_fkey'), 'clubs_and_players', type_='foreignkey')
    op.drop_constraint(op.f('clubs_and_players_player id_fkey'), 'clubs_and_players', type_='foreignkey')
    op.create_foreign_key(None, 'clubs_and_players', 'players', ['player id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clubs_and_players', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('players_club_id_fkey'), 'players', type_='foreignkey')
    op.drop_column('players', 'club_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('club_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('players_club_id_fkey'), 'players', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'clubs_and_players', type_='foreignkey')
    op.drop_constraint(None, 'clubs_and_players', type_='foreignkey')
    op.create_foreign_key(op.f('clubs_and_players_player id_fkey'), 'clubs_and_players', 'players', ['player id'], ['id'])
    op.create_foreign_key(op.f('clubs_and_players_club_id_fkey'), 'clubs_and_players', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###
