"""player_id M2M

Revision ID: 823f834526ce
Revises: 396597d6ee57
Create Date: 2025-12-21 02:19:18.827345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823f834526ce'
down_revision: Union[str, Sequence[str], None] = '396597d6ee57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs_and_players', sa.Column('player_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('clubs_and_players_player id_fkey'), 'clubs_and_players', type_='foreignkey')
    op.create_foreign_key(None, 'clubs_and_players', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.drop_column('clubs_and_players', 'player id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs_and_players', sa.Column('player id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clubs_and_players', type_='foreignkey')
    op.create_foreign_key(op.f('clubs_and_players_player id_fkey'), 'clubs_and_players', 'players', ['player id'], ['id'], ondelete='CASCADE')
    op.drop_column('clubs_and_players', 'player_id')
    # ### end Alembic commands ###
