"""clubs cascade2

Revision ID: c041dc32dec4
Revises: 214810def148
Create Date: 2025-12-20 03:25:04.425210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c041dc32dec4'
down_revision: Union[str, Sequence[str], None] = '214810def148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('players_club_id_fkey'), 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'clubs', ['club_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key(op.f('players_club_id_fkey'), 'players', 'clubs', ['club_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
