"""user+shares & exchange+owner and cascade

Revision ID: dd27d46b6a01
Revises: db814c9dedde
Create Date: 2025-12-20 03:10:28.441477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd27d46b6a01'
down_revision: Union[str, Sequence[str], None] = 'db814c9dedde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
